Update csv
project-io-group/vmms-backend pull request #12
Opened 2018-06-05 21:44 UTC by maxiwoj

Fixed the bugs with eager loading on import

2018-06-06 09:00 UTC, luknw requested changes

2018-06-06 09:00 UTC, luknw commented on src/main/java/pl/agh/edu/iisg/io/vmms/vmmsbackend/controller/VMPoolController.java
> +            vmPoolsNumber = updateVmPools(file, vmPoolsNumber, false);
What is the purpose of passing vmPoolsNumber as parameter if it's always 0?

2018-06-06 09:00 UTC, luknw commented on src/main/java/pl/agh/edu/iisg/io/vmms/vmmsbackend/controller/VMPoolController.java
> +                        errors.append("Error in line ").append(lines).append(": ").append(e.getMessage()).append("\n");
I guess String.format would be more readable.

2018-06-06 09:00 UTC, luknw commented on src/main/java/pl/agh/edu/iisg/io/vmms/vmmsbackend/controller/VMPoolController.java
> +                        errors.append("Can not delete pool ").append(deleted.getDisplayName()).append(" with trailing reservations!\n");
Cannot or can't. Can not looks awkward xDD

2018-06-06 09:00 UTC, luknw commented on src/main/java/pl/agh/edu/iisg/io/vmms/vmmsbackend/controller/VMPoolController.java
> +            if(errors.length() != 0){
!errors.isEmpty()

2018-06-06 09:00 UTC, luknw commented on src/main/java/pl/agh/edu/iisg/io/vmms/vmmsbackend/controller/VMPoolController.java
> +    private int updateVmPools(@RequestParam("file") MultipartFile file, int vmPoolsNumber, boolean replace) throws VMPoolImportFileException {
Is the RequestParam annotation necessary here?

2018-06-06 09:00 UTC, luknw commented on src/main/java/pl/agh/edu/iisg/io/vmms/vmmsbackend/controller/VMPoolController.java
> +    private int updateVmPools(@RequestParam("file") MultipartFile file, int vmPoolsNumber, boolean replace) throws VMPoolImportFileException {
I don't like http path mapping and update logic mixed up in one class. I'd extract the update logic to external class + maybe link it with some service.

2018-06-06 09:00 UTC, luknw commented on src/main/java/pl/agh/edu/iisg/io/vmms/vmmsbackend/controller/VMPoolController.java
> +    private boolean processVmPool(List<VMPool> vmPools, VMPool newPool, VMPool found) throws VMPoolImportFileException {
The found parameter is cryptic. I think it would be better to perform the search inside this method and remove the parameter.

2018-06-11 19:04 UTC, Peantab approved these changes

2018-06-11 19:04 UTC, Peantab commented on src/main/java/pl/agh/edu/iisg/io/vmms/vmmsbackend/controller/VMPoolController.java
> +    @RequestMapping(value = "/update", method = RequestMethod.POST)
Hmmm, nowy endpoint i nowy brak aktualizacji w README.md?
[technicznie rzecz biorąc jest to informacja o tym, że Admin Guide może na jutro nie powstać]

2018-06-11 19:05 UTC, merged